apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/nadstation/rpi-devops-lab-backend:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: devuser
            - name: DB_PASSWORD
              value: devpassword
            - name: DB_NAME
              value: devlab
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
